#!/usr/bin/env bash
# installs load balancer
apt-get update
Sudo apt update -y
sudo apt install haproxy -y
echo "frontend web-front
        bind *:80
        default_backend web-backend
backend web-backend
        balance roundrobin
        server web1 3.238.106.249:80 check
        server web2 3.239.115.217:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
