#!/usr/bin/env bash
# installs load balancer
apt-get update
Sudo apt update -y
sudo apt install haproxy -y
echo "frontend webfront
        bind *:80
        default_backend webbackend
backend webbackend
        balance roundrobin
        server web1 54.165.153.45:80 check
        server web2 54.162.87.125:80 check
" | sudo tee -a /etc/haproxy/haproxy.cfg
sudo service haproxy restart
