#!/usr/bin/env bash
# Using a for loop to list files in the current directory
for file in *
do
    # Check if the file is not hidden (doesn't start with a dot)
    if [ "${file}" != ".*" ]
    then
        # Extract the part after the first dash using the cut command
        display_name=$(echo "$file" | cut -d'-' -f2-)
        echo "$display_name"
    fi
done
